version: '3'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: laravel
    ports:
      - 81:80
    volumes: 
      - ./siteroot:/srv/app
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel_docker
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - 'db:/var/lib/mysql'
  redis:
    image: redis:6.0-alpine
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes: 
    db:

